In [3]:
import pandas as pd

col_names = ['Club', 'Age16', 'TMV16'] #TMV - Total Market Value
s16=pd.read_csv('teams/laliga16.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s16['TMV16'] = s16['TMV16'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age15', 'TMV15']
s15=pd.read_csv('teams/laliga15.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s15['TMV15'] = s15['TMV15'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age14', 'TMV14']
s14=pd.read_csv('teams/laliga14.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s14['TMV14'] = s14['TMV14'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age13', 'TMV13']
s13=pd.read_csv('teams/laliga13.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s13['TMV13'] = s13['TMV13'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age12', 'TMV12']
s12=pd.read_csv('teams/laliga12.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s12['TMV12'] = s12['TMV12'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age11', 'TMV11']
s11=pd.read_csv('teams/laliga11.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s11['TMV11'] = s11['TMV11'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age10', 'TMV10']
s10=pd.read_csv('teams/laliga10.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s10['TMV10'] = s10['TMV10'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age09', 'TMV09']
s09=pd.read_csv('teams/laliga09.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s09['TMV09'] = s09['TMV09'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age08', 'TMV08']
s08=pd.read_csv('teams/laliga08.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s08['TMV08'] = s08['TMV08'].str.extract('(\d+)').astype(int)

/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:5: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:9: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:13: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:17: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:21: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:25: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:29: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:33: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:37: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

In [7]:
laliga = pd.merge(s16, s15, how="outer", on=['Club'])
#laliga = pd.merge(laliga, s14, how="outer", on=['Club'])
#laliga = pd.merge(laliga, s13, how="outer", on=['Club'])
#laliga = pd.merge(laliga, s12, how="outer", on=['Club'])
#laliga = pd.merge(laliga, s11, how="outer", on=['Club'])
#laliga = pd.merge(laliga, s10, how="outer", on=['Club'])
#laliga = pd.merge(laliga, s09, how="outer", on=['Club'])
#laliga = pd.merge(laliga, s08, how="outer", on=['Club'])

laliga

                      Club  Age16  TMV16  Age15  TMV15
0              Real Madrid   27.2  764.0   23.8  700.0
1             FC Barcelona   27.3  758.0   24.9  618.0
2          Atlético Madrid   27.7  501.0   24.4  336.0
3               Sevilla FC   27.6  236.0   24.8  186.0
4              Valencia CF   26.3  185.0   22.7  254.0
5            Villarreal CF   27.9  174.0   24.4  115.0
6          Athletic Bilbao   27.7  157.0   26.0  122.0
7            Real Sociedad   26.7  114.0   24.6  122.0
8            Celta de Vigo   26.3  105.0   23.6   63.0
9                Málaga CF   27.2   77.0   26.0   78.0
10           UD Las Palmas   27.8   70.0   26.2   29.0
11  RCD Espanyol Barcelona   27.8   68.0   24.1   61.0
12  Deportivo de La Coruña   28.2   65.0   27.4   51.0
13     Real Betis Balompié   27.1   64.0   25.9   72.0
14        Deportivo Alavés   26.3   62.0    NaN    NaN
15              Granada CF   25.1   57.0   24.9   73.0
16                SD Eibar   27.3   53.0   24.8   45.0
17          Sporting Gijón   26.9   48.0   23.8   30.0
18              CD Leganés   27.0   43.0    NaN    NaN
19              CA Osasuna   27.5   38.0    NaN    NaN
20              Levante UD    NaN    NaN   26.3   68.0
21               Getafe CF    NaN    NaN   24.7   55.0
22          Rayo Vallecano    NaN    NaN   27.0   53.0

In [130]:
col_names = ['Club', 'Age16', 'TMV16'] #TMV - Total Market Value
s16=pd.read_csv('teams/PL16.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s16['TMV16'] = s16['TMV16'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age15', 'TMV15']
s15=pd.read_csv('teams/PL15.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s15['TMV15'] = s15['TMV15'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age14', 'TMV14']
s14=pd.read_csv('teams/PL14.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s14['TMV14'] = s14['TMV14'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age13', 'TMV13']
s13=pd.read_csv('teams/PL13.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s13['TMV13'] = s13['TMV13'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age12', 'TMV12']
s12=pd.read_csv('teams/PL12.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s12['TMV12'] = s12['TMV12'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age11', 'TMV11']
s11=pd.read_csv('teams/PL11.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s11['TMV11'] = s11['TMV11'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age10', 'TMV10']
s10=pd.read_csv('teams/PL10.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s10['TMV10'] = s10['TMV10'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age09', 'TMV09']
s09=pd.read_csv('teams/PL09.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s09['TMV09'] = s09['TMV09'].str.extract('(\d+)').astype(int)

col_names = ['Club', 'Age08', 'TMV08']
s08=pd.read_csv('teams/PL08.csv', sep=',', usecols=[2,5,7], header=0, names = col_names, skiprows=1, decimal=',')
s08['TMV08'] = s08['TMV08'].str.extract('(\d+)').astype(int)


pl = pd.merge(s16, s15, how="outer", on=['Club'])
pl = pd.merge(pl, s14, how="outer", on=['Club'])
pl = pd.merge(pl, s13, how="outer", on=['Club'])
pl = pd.merge(pl, s12, how="outer", on=['Club'])
pl = pd.merge(pl, s11, how="outer", on=['Club'])
pl = pd.merge(pl, s10, how="outer", on=['Club'])
pl = pd.merge(pl, s09, how="outer", on=['Club'])
pl = pd.merge(pl, s08, how="outer", on=['Club'])

/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  app.launch_new_instance()
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:7: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:11: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:15: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:19: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:23: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:27: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:31: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
/home/domino/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:35: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

In [131]:
pl

,Club,Age16,TMV16,Age15,TMV15,Age14,TMV14,Age13,TMV13,Age12,TMV12,Age11,TMV11,Age10,TMV10,Age09,TMV09,Age08,TMV08
0,Manchester City,28.3,525.0,24.4,452.0,25.4,478.0,25.7,479.0,24.0,510.0,24.7,461.0,23.4,382.0,24.1,314.0,24.0,206.0
1,Chelsea FC,26.6,515.0,23.7,579.0,23.9,526.0,23.8,582.0,25.3,408.0,26.3,467.0,24.5,446.0,26.8,443.0,25.6,406.0
2,Arsenal FC,27.2,492.0,23.7,408.0,23.0,404.0,23.8,332.0,23.8,293.0,23.3,312.0,23.4,304.0,21.7,281.0,21.3,250.0
3,Manchester United,27.0,466.0,22.5,374.0,23.9,522.0,24.9,511.0,24.1,444.0,23.6,398.0,24.1,384.0,25.0,362.0,24.3,356.0
4,Tottenham Hotspur,25.3,429.0,22.7,253.0,23.7,298.0,23.4,296.0,25.1,309.0,24.2,316.0,24.7,296.0,23.3,249.0,22.5,212.0
5,Liverpool FC,25.7,372.0,22.5,325.0,23.4,285.0,23.8,272.0,22.8,275.0,25.0,247.0,23.5,365.0,24.4,336.0,23.9,257.0
6,Everton FC,27.0,252.0,24.7,204.0,24.3,177.0,25.9,217.0,25.6,124.0,25.6,190.0,23.9,178.0,23.1,221.0,24.4,162.0
7,Southampton FC,26.2,230.0,24.1,187.0,23.5,150.0,23.9,102.0,24.3,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,West Ham United,27.1,209.0,23.2,185.0,24.8,123.0,25.3,128.0,25.1,114.0,NaN,NaN,25.1,158.0,23.8,118.0,24.3,80.0
9,Leicester City,27.7,205.0,25.9,91.0,25.9,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Crystal Palace,28.9,186.0,25.6,121.0,26.0,89.0,26.2,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Stoke City,29.3,168.0,26.3,127.0,26.4,128.0,26.1,126.0,27.6,99.0,27.9,119.0,27.0,96.0,25.9,76.0,26.6,49.0
12,Swansea City,27.7,127.0,24.8,138.0,24.3,107.0,25.5,118.0,25.9,88.0,24.8,40.0,NaN,NaN,NaN,NaN,NaN,NaN
13,Watford FC,29.0,127.0,26.4,110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Hull City,27.1,112.0,NaN,NaN,26.1,122.0,26.4,69.0,NaN,NaN,NaN,NaN,NaN,NaN,26.0,75.0,27.2,38.0
15,AFC Bournemouth,26.4,106.0,24.1,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Sunderland AFC,27.1,102.0,25.5,128.0,24.8,115.0,24.9,151.0,25.4,127.0,25.0,125.0,23.7,137.0,24.5,131.0,24.9,91.0
17,Middlesbrough FC,27.9,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.3,73.0
18,West Bromwich Albion,28.6,95.0,25.4,117.0,25.5,100.0,26.6,91.0,25.7,83.0,25.0,81.0,24.3,85.0,NaN,NaN,24.6,64.0
19,Burnley FC,28.2,85.0,NaN,NaN,25.5,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,38.0,NaN,NaN
20,Newcastle United,NaN,NaN,23.6,200.0,22.9,139.0,24.4,188.0,24.1,190.0,24.1,120.0,23.7,95.0,NaN,NaN,24.8,134.0
21,Aston Villa,NaN,NaN,23.5,112.0,24.3,127.0,24.0,116.0,24.1,101.0,25.3,157.0,25.1,207.0,25.5,160.0,25.4,111.0
22,Norwich City,NaN,NaN,25.6,103.0,NaN,NaN,26.2,95.0,25.3,70.0,24.5,22.0,NaN,NaN,NaN,NaN,NaN,NaN
23,Queens Park Rangers,NaN,NaN,NaN,NaN,25.1,115.0,NaN,NaN,28.1,150.0,27.0,106.0,NaN,NaN,NaN,NaN,NaN,NaN
24,Fulham FC,NaN,NaN,NaN,NaN,NaN,NaN,25.4,148.0,26.9,114.0,26.1,118.0,27.5,111.0,25.3,92.0,25.3,73.0
25,Cardiff City,NaN,NaN,NaN,NaN,NaN,NaN,24.6,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Wigan Athletic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,81.0,25.4,70.0,24.0,72.0,25.4,73.0,25.7,61.0
27,Reading FC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.6,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Bolton Wanderers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.2,98.0,25.4,93.0,25.3,85.0,24.6,82.0
29,Blackburn Rovers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.5,90.0,25.1,95.0,25.3,90.0,26.4,86.0
30,Wolverhampton Wanderers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.1,82.0,23.7,76.0,24.1,59.0,NaN,NaN
31,Birmingham City,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.8,102.0,25.5,63.0,NaN,NaN
32,Blackpool FC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.3,38.0,NaN,NaN,NaN,NaN
33,Portsmouth FC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.4,99.0,26.8,131.0

In [135]:
frames = [laliga, pl]
teams = pd.concat(frames)
len(teams)

69

In [134]:
teams.to_csv('teamsAgeTMV.csv')